### ISSUE TITLE
I got a .blob file..???

### ISSUE THREAD

**Issue by Logic-Elliven** [m417z/winbindex#169]
Hi 
Interesting app

I went to:  https://winbindex.m417z.com/  (correct?)
and searched for the file:  resampledmo.dll

I ended up with: 
A526E27F5718054E3C1CC0E711891916C51097F16C99B0258D046EB7CB54E32800.blob  (Attached, but renamed to .txt as .blob isnt allowed)
er...? ok??
Ran that through VT and got:
https://www.virustotal.com/gui/file/70d563bda75f3f3f3b110fa01085c6f40e0191befee964d7aa46cbf985d83dfc/behavior
Which seems like the result for the correct file.

At this point I was like: "WTF!?  Am I missing something here??

[A526E27F5718054E3C1CC0E711891916C51097F16C99B0258D046EB7CB54E32800.txt](https://github.com/m417z/winbindex/files/11852404/A526E27F5718054E3C1CC0E711891916C51097F16C99B0258D046EB7CB54E32800.txt)

**Comment by m417z** [comment]
Hi,

Just rename it to the file name you need, such as `resampledmo.dll`.
Note that Winbindex can't rename the file for you, it's a known limitation because the files are hosted on Microsoft servers, but there's [a userscript](https://gist.github.com/m417z/3c6016b0c9d42b3a8692874d28954786) to help with this. See this issue for more details: https://github.com/m417z/winbindex/issues/1

**Comment by Logic-Elliven** [comment]
Thx :)
